name: Twitter Auto Liker

on:
  schedule:
    # Run every 5 hours
    - cron: '0 */5 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  like-tweets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Run Twitter liker
      env:
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
        TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        PROFILE_URL: ${{ secrets.PROFILE_URL }}
      run: |
        node twitter_like_manager_single_login.js "$PROFILE_URL" 